network:
  - dim: 512
    aggr: 'concat'
    loss: 'sigmoid'
    arch: '1-1-0'
    act: 'relu'
    bias: 'norm'

params:
  - model: 'sage'
    lr: 0.02
    dropout: 0.1
    weight_decay: 0.000005
    sample_coverage: 50

phase:
  - end: 50
    sampler: 'ff'
    sample_rate: 0.05
    p: 0.5
    core_rate: 1  #gamma
    per_sample_num: 2000